<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelmanagement"
    nsURI="http:///uml13.modelmanagement.ecore" nsPrefix="modelmanagement">
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="foundation.ecore#//core/GeneralizableElement foundation.ecore#//core/Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedElement" upperBound="-1"
        eType="#//ElementImport" containment="true" eOpposite="#//ElementImport/package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subsystem" eSuperTypes="foundation.ecore#//core/Classifier #//Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInstantiable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EEnum foundation.ecore#//datatypes/VisibilityKind"
        defaultValueLiteral="public"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType foundation.ecore#//datatypes/Name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="#//Package" transient="true" eOpposite="#//Package/importedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" lowerBound="1"
        eType="ecore:EClass foundation.ecore#//core/ModelElement" eOpposite="foundation.ecore#//core/ModelElement/elementImport"/>
  </eClassifiers>
</ecore:EPackage>
