<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behavioralelements"
    nsURI="http:///umlmia.behavioralelements.ecore" nsPrefix="behavioralelements">
  <eSubpackages name="activitygraphs" nsURI="http:///umlmia.behavioralelements/activitygraphs.ecore"
      nsPrefix="behavioralelements.activitygraphs">
    <eClassifiers xsi:type="ecore:EClass" name="UMLActionState" eSuperTypes="#//statemachines/UMLCompositeState">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicMultiplicity"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicArguments" upperBound="-1"
          eType="#//activitygraphs/UMLArgumentList" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLActivityGraph" eSuperTypes="#//statemachines/UMLStateMachine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="partitions" upperBound="-1"
          eType="#//activitygraphs/UMLPartition" containment="true" eOpposite="#//activitygraphs/UMLPartition/activityGraph"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLArgumentList">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//commonbehavior/UMLArgument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLClassifierInState" eSuperTypes="foundation.ecore#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inStates" lowerBound="1"
          upperBound="-1" eType="#//statemachines/UMLState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLObjectFlowState" eSuperTypes="#//statemachines/UMLCompositeState">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSynch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="ecore:EClass foundation.ecore#//core/UMLParameter" eOpposite="foundation.ecore#//core/UMLParameter/states"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLPartition" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activityGraph" lowerBound="1"
          eType="#//activitygraphs/UMLActivityGraph" transient="true" eOpposite="#//activitygraphs/UMLActivityGraph/partitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
          eType="ecore:EClass foundation.ecore#//core/UMLModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSubactivityState" eSuperTypes="#//statemachines/UMLSubmachineState">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamicMultiplicity"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicArguments" upperBound="-1"
          eType="#//activitygraphs/UMLArgumentList" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLCallState" eSuperTypes="#//activitygraphs/UMLActionState"/>
  </eSubpackages>
  <eSubpackages name="collaborations" nsURI="http:///umlmia.behavioralelements/collaborations.ecore"
      nsPrefix="behavioralelements.collaborations">
    <eClassifiers xsi:type="ecore:EClass" name="UMLCollaboration" eSuperTypes="foundation.ecore#//core/UMLGeneralizableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interactions" upperBound="-1"
          eType="#//collaborations/UMLInteraction" containment="true" eOpposite="#//collaborations/UMLInteraction/context"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usedCollaborations" upperBound="-1"
          eType="#//collaborations/UMLCollaboration" eOpposite="#//collaborations/UMLCollaboration/collaborations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="collaborations" upperBound="-1"
          eType="#//collaborations/UMLCollaboration" eOpposite="#//collaborations/UMLCollaboration/usedCollaborations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstances" lowerBound="1"
          upperBound="-1" eType="#//commonbehavior/UMLInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLinks" upperBound="-1"
          eType="#//commonbehavior/UMLLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="representedClassifier"
          eType="ecore:EClass foundation.ecore#//core/UMLClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="representedOperation"
          eType="ecore:EClass foundation.ecore#//core/UMLOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLInteraction" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//collaborations/UMLCollaboration" transient="true" eOpposite="#//collaborations/UMLCollaboration/interactions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messages" lowerBound="1"
          upperBound="-1" eType="#//collaborations/UMLMessage" containment="true"
          eOpposite="#//collaborations/UMLMessage/interaction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLMessage" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" lowerBound="1"
          eType="#//collaborations/UMLInteraction" transient="true" eOpposite="#//collaborations/UMLInteraction/messages"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activator" eType="#//collaborations/UMLMessage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
          eType="#//collaborations/UMLMessage" eOpposite="#//collaborations/UMLMessage/predecessors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="predecessors" upperBound="-1"
          eType="#//collaborations/UMLMessage" eOpposite="#//collaborations/UMLMessage/successors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//commonbehavior/UMLInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLink" eType="#//commonbehavior/UMLLink"
          eOpposite="#//commonbehavior/UMLLink/messages"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
          eType="#//commonbehavior/UMLInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
          eType="#//commonbehavior/UMLAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
          eType="#//commonbehavior/UMLInstance"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="commonbehavior" nsURI="http:///umlmia.behavioralelements/commonbehavior.ecore"
      nsPrefix="behavioralelements.commonbehavior">
    <eClassifiers xsi:type="ecore:EClass" name="UMLUninterpretedAction" eSuperTypes="#//commonbehavior/UMLAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAction" abstract="true" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="recurrence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAsynchronous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actualArguments" upperBound="-1"
          eType="#//commonbehavior/UMLArgument" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLActionSequence" eSuperTypes="#//commonbehavior/UMLAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
          eType="#//commonbehavior/UMLAction" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLArgument" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAssignmentAction" eSuperTypes="#//commonbehavior/UMLAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAttributeLink" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" eType="#//commonbehavior/UMLInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLAttribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLCallAction" eSuperTypes="#//commonbehavior/UMLAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLComponentInstance" eSuperTypes="#//commonbehavior/UMLInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="residents" upperBound="-1"
          eType="#//commonbehavior/UMLInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLCreateAction" eSuperTypes="#//commonbehavior/UMLAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiation" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLDataValue" eSuperTypes="#//commonbehavior/UMLInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLDestroyAction" eSuperTypes="#//commonbehavior/UMLAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLInstance" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkEnds" upperBound="-1"
          eType="#//commonbehavior/UMLLinkEnd" eOpposite="#//commonbehavior/UMLLinkEnd/instance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="slots" upperBound="-1"
          eType="#//commonbehavior/UMLAttributeLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstances" upperBound="-1"
          eType="#//commonbehavior/UMLInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLinks" upperBound="-1"
          eType="#//commonbehavior/UMLLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLLink" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
          eType="#//collaborations/UMLMessage" eOpposite="#//collaborations/UMLMessage/communicationLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" lowerBound="2"
          upperBound="-1" eType="#//commonbehavior/UMLLinkEnd" containment="true"
          eOpposite="#//commonbehavior/UMLLinkEnd/link"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stimulus" upperBound="-1"
          eType="#//commonbehavior/UMLStimulus" eOpposite="#//commonbehavior/UMLStimulus/communicationLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLAssociation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLLinkEnd" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instance" lowerBound="1"
          eType="#//commonbehavior/UMLInstance" eOpposite="#//commonbehavior/UMLInstance/linkEnds"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1"
          eType="#//commonbehavior/UMLLink" transient="true" eOpposite="#//commonbehavior/UMLLink/connections"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiedValues" upperBound="-1"
          eType="#//commonbehavior/UMLAttributeLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLAssociationEnd"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLLinkObject" eSuperTypes="#//commonbehavior/UMLObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1"
          eType="#//commonbehavior/UMLLink"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLNodeInstance" eSuperTypes="#//commonbehavior/UMLInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="residents" upperBound="-1"
          eType="#//commonbehavior/UMLComponentInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLObject" eSuperTypes="#//commonbehavior/UMLInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLReturnAction" eSuperTypes="#//commonbehavior/UMLAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSendAction" eSuperTypes="#//commonbehavior/UMLAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
          eType="#//commonbehavior/UMLSignal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLTerminateAction" eSuperTypes="#//commonbehavior/UMLAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLReception" eSuperTypes="foundation.ecore#//core/UMLOperation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
          eType="#//commonbehavior/UMLSignal" eOpposite="#//commonbehavior/UMLSignal/receptions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLException" eSuperTypes="#//commonbehavior/UMLSignal"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSignal" eSuperTypes="foundation.ecore#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="receptions" upperBound="-1"
          eType="#//commonbehavior/UMLReception" eOpposite="#//commonbehavior/UMLReception/signal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="occurrences" upperBound="-1"
          eType="#//statemachines/UMLSignalEvent" eOpposite="#//statemachines/UMLSignalEvent/signal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
          eType="ecore:EClass foundation.ecore#//core/UMLOperation" eOpposite="foundation.ecore#//core/UMLOperation/raisedSignals"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSubsystemInstance" eSuperTypes="#//commonbehavior/UMLInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLStimulus" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dispatchAction" lowerBound="1"
          eType="#//commonbehavior/UMLAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
          eType="#//commonbehavior/UMLInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
          eType="#//commonbehavior/UMLInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#//commonbehavior/UMLInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="communicationLink" eType="#//commonbehavior/UMLLink"
          eOpposite="#//commonbehavior/UMLLink/stimulus"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="statemachines" nsURI="http:///umlmia.behavioralelements/statemachines.ecore"
      nsPrefix="behavioralelements.statemachines">
    <eClassifiers xsi:type="ecore:EClass" name="UMLCallEvent" eSuperTypes="#//statemachines/UMLEvent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
          eType="ecore:EClass foundation.ecore#//core/UMLOperation" eOpposite="foundation.ecore#//core/UMLOperation/occurrences"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLChangeEvent" eSuperTypes="#//statemachines/UMLEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLCompositeState" eSuperTypes="#//statemachines/UMLState">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConcurrent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subvertexes" upperBound="-1"
          eType="#//statemachines/UMLStateVertex" containment="true" eOpposite="#//statemachines/UMLStateVertex/container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLEvent" abstract="true" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="ecore:EClass foundation.ecore#//core/UMLParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLFinalState" eSuperTypes="#//statemachines/UMLState"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLGuard" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLPseudoState" eSuperTypes="#//statemachines/UMLStateVertex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EEnum enumerations.ecore#//PseudostateKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSignalEvent" eSuperTypes="#//statemachines/UMLEvent">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
          eType="#//commonbehavior/UMLSignal" eOpposite="#//commonbehavior/UMLSignal/occurrences"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLState" eSuperTypes="#//statemachines/UMLStateVertex">
      <eStructuralFeatures xsi:type="ecore:EReference" name="doActivity" eType="#//commonbehavior/UMLAction"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//commonbehavior/UMLAction"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//commonbehavior/UMLAction"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//statemachines/UMLStateMachine"
          transient="true" eOpposite="#//statemachines/UMLStateMachine/top"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deferrableEvents" upperBound="-1"
          eType="#//statemachines/UMLEvent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="internals" upperBound="-1"
          eType="#//statemachines/UMLTransition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLStateMachine" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="ecore:EClass foundation.ecore#//core/UMLModelElement"
          eOpposite="foundation.ecore#//core/UMLModelElement/behaviors"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="top" lowerBound="1" eType="#//statemachines/UMLState"
          containment="true" eOpposite="#//statemachines/UMLState/stateMachine"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
          eType="#//statemachines/UMLTransition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLStateVertex" abstract="true" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoings" upperBound="-1"
          eType="#//statemachines/UMLTransition" eOpposite="#//statemachines/UMLTransition/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//statemachines/UMLCompositeState"
          transient="true" eOpposite="#//statemachines/UMLCompositeState/subvertexes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomings" upperBound="-1"
          eType="#//statemachines/UMLTransition" eOpposite="#//statemachines/UMLTransition/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLStubState" eSuperTypes="#//statemachines/UMLStateVertex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSubmachineState" eSuperTypes="#//statemachines/UMLCompositeState">
      <eStructuralFeatures xsi:type="ecore:EReference" name="submachine" lowerBound="1"
          eType="#//statemachines/UMLStateMachine"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSynchState" eSuperTypes="#//statemachines/UMLStateVertex">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLTimeEvent" eSuperTypes="#//statemachines/UMLEvent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLTransition" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="#//commonbehavior/UMLAction"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//statemachines/UMLStateVertex" eOpposite="#//statemachines/UMLStateVertex/outgoings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//statemachines/UMLStateVertex" eOpposite="#//statemachines/UMLStateVertex/incomings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//statemachines/UMLGuard"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//statemachines/UMLEvent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLSimpleState" eSuperTypes="#//statemachines/UMLState"/>
  </eSubpackages>
  <eSubpackages name="usecases" nsURI="http:///umlmia.behavioralelements/usecases.ecore"
      nsPrefix="behavioralelements.usecases">
    <eClassifiers xsi:type="ecore:EClass" name="UMLActor" eSuperTypes="foundation.ecore#//core/UMLClassifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLExtend" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extension" lowerBound="1"
          eType="#//usecases/UMLUseCase" eOpposite="#//usecases/UMLUseCase/extends"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1"
          eType="#//usecases/UMLUseCase"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoints" upperBound="-1"
          eType="#//usecases/UMLExtensionPoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLInclude" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1"
          eType="#//usecases/UMLUseCase" eOpposite="#//usecases/UMLUseCase/includes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="addition" lowerBound="1"
          eType="#//usecases/UMLUseCase"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLUseCase" eSuperTypes="foundation.ecore#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="includes" upperBound="-1"
          eType="#//usecases/UMLInclude" eOpposite="#//usecases/UMLInclude/base"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
          eType="#//usecases/UMLExtend" eOpposite="#//usecases/UMLExtend/extension"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extensionPoints" upperBound="-1"
          eType="#//usecases/UMLExtensionPoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLUseCaseInstance" eSuperTypes="#//commonbehavior/UMLInstance"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLExtensionPoint" eSuperTypes="foundation.ecore#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
