<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="enumerations"
    nsURI="http:///umlmia.enumerations.ecore" nsPrefix="enumerations">
  <eClassifiers xsi:type="ecore:EEnum" name="PseudostateKind">
    <eLiterals name="initial"/>
    <eLiterals name="deepHistory" value="1"/>
    <eLiterals name="shallowHistory" value="2"/>
    <eLiterals name="join" value="3"/>
    <eLiterals name="fork" value="4"/>
    <eLiterals name="branch" value="5"/>
    <eLiterals name="junction" value="6"/>
    <eLiterals name="final" value="7"/>
    <eLiterals name="choice" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DocumentKind">
    <eLiterals name="file"/>
    <eLiterals name="url" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PersistenceKind">
    <eLiterals name="transient"/>
    <eLiterals name="persistent" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="public"/>
    <eLiterals name="protected" value="1"/>
    <eLiterals name="private" value="2"/>
    <eLiterals name="package" value="3"/>
    <eLiterals name="implementation" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrderingKind">
    <eLiterals name="ordered"/>
    <eLiterals name="unordered" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
    <eLiterals name="none"/>
    <eLiterals name="aggregate" value="1"/>
    <eLiterals name="composite" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeKind">
    <eLiterals name="instance"/>
    <eLiterals name="classifier" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeableKind">
    <eLiterals name="changeable"/>
    <eLiterals name="frozen" value="1"/>
    <eLiterals name="addOnly" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallConcurrencyKind">
    <eLiterals name="concurrent"/>
    <eLiterals name="guarded" value="1"/>
    <eLiterals name="sequential" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirectionKind">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2"/>
    <eLiterals name="return" value="3"/>
  </eClassifiers>
</ecore:EPackage>
