<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="foundation"
    nsURI="http:///foundation.ecore" nsPrefix="foundation">
  <eSubpackages name="core" nsURI="http:///foundation/core.ecore" nsPrefix="foundation.core">
    <eClassifiers xsi:type="ecore:EClass" name="UMLAbstraction" eSuperTypes="#//core/UMLDependency">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLBinding" eSuperTypes="#//core/UMLDependency">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" lowerBound="1"
          upperBound="-1" eType="#//core/UMLModelElement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLComponent" eSuperTypes="#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="residents" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/implementationLocations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentLocations"
          upperBound="-1" eType="#//core/UMLNode" eOpposite="#//core/UMLNode/residents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementations" upperBound="-1"
          eType="#//core/UMLArtifact" eOpposite="#//core/UMLArtifact/implementationComponents"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLDependency" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/clientDependencies"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="suppliers" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/supplierDependencies"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLDocument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum enumerations.ecore#//DocumentKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLNode" eSuperTypes="#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="residents" upperBound="-1"
          eType="#//core/UMLComponent" eOpposite="#//core/UMLComponent/deploymentLocations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLPermission" eSuperTypes="#//core/UMLDependency"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLUsage" eSuperTypes="#//core/UMLDependency"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAssociation" eSuperTypes="#//core/UMLGeneralizableElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistence" eType="ecore:EEnum enumerations.ecore#//PersistenceKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" lowerBound="2"
          upperBound="-1" eType="#//core/UMLAssociationEnd" containment="true" eOpposite="#//core/UMLAssociationEnd/association"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationClass" eType="#//core/UMLAssociationClass"
          eOpposite="#//core/UMLAssociationClass/association"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
          eType="ecore:EClass generalmechanisms.ecore#//UMLPackage" transient="true"
          eOpposite="generalmechanisms.ecore#//UMLPackage/ownedAssociations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAssociationClass" eSuperTypes="#//core/UMLClass">
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
          eType="#//core/UMLAssociation" eOpposite="#//core/UMLAssociation/associationClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAssociationEnd" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EEnum enumerations.ecore#//OrderingKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="ecore:EEnum enumerations.ecore#//AggregationKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" eType="ecore:EEnum enumerations.ecore#//ScopeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" eType="ecore:EEnum enumerations.ecore#//ChangeableKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="association" lowerBound="1"
          eType="#//core/UMLAssociation" transient="true" eOpposite="#//core/UMLAssociation/connections"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiers" upperBound="-1"
          eType="#//core/UMLAttribute" containment="true" eOpposite="#//core/UMLAttribute/associationEnd"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/UMLClassifier" eOpposite="#//core/UMLClassifier/associationEnds"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLAttribute" eSuperTypes="#//core/UMLFeature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" eType="ecore:EEnum enumerations.ecore#//ChangeableKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetScope" eType="ecore:EEnum enumerations.ecore#//ScopeKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EEnum enumerations.ecore#//OrderingKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistence" eType="ecore:EEnum enumerations.ecore#//PersistenceKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1"
          eType="#//core/UMLClassifier" transient="true" eOpposite="#//core/UMLClassifier/attributes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/UMLClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnd" eType="#//core/UMLAssociationEnd"
          transient="true" eOpposite="#//core/UMLAssociationEnd/qualifiers"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLClass" eSuperTypes="#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistence" eType="ecore:EEnum enumerations.ecore#//PersistenceKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLClassifier" abstract="true" eSuperTypes="#//core/UMLGeneralizableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//core/UMLAttribute" containment="true" eOpposite="#//core/UMLAttribute/owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentClassifier" lowerBound="1"
          eType="#//core/UMLClassifier" transient="true" eOpposite="#//core/UMLClassifier/nestedClassifiers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nestedClassifiers" upperBound="-1"
          eType="#//core/UMLClassifier" containment="true" eOpposite="#//core/UMLClassifier/parentClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
          eType="#//core/UMLOperation" containment="true" eOpposite="#//core/UMLOperation/owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="associationEnds" upperBound="-1"
          eType="#//core/UMLAssociationEnd" eOpposite="#//core/UMLAssociationEnd/type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="importedInPackages" upperBound="-1"
          eType="ecore:EClass generalmechanisms.ecore#//UMLClassifierImport" eOpposite="generalmechanisms.ecore#//UMLClassifierImport/importedClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
          eType="ecore:EClass generalmechanisms.ecore#//UMLPackage" transient="true"
          eOpposite="generalmechanisms.ecore#//UMLPackage/ownedClassifiers"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLConstraint" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedElements"
          lowerBound="1" upperBound="-1" eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/constraints"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedStereotype"
          eType="#//extensionmechanisms/UMLStereotype" transient="true" eOpposite="#//extensionmechanisms/UMLStereotype/stereotypeConstraints"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLDataType" eSuperTypes="#//core/UMLClassifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLFeature" abstract="true" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerScope" eType="ecore:EEnum enumerations.ecore#//ScopeKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLGeneralizableElement" abstract="true"
        eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generalizations" upperBound="-1"
          eType="#//core/UMLGeneralization" eOpposite="#//core/UMLGeneralization/child"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="specializations" upperBound="-1"
          eType="#//core/UMLGeneralization" containment="true" eOpposite="#//core/UMLGeneralization/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLGeneralization" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discriminator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1"
          eType="#//core/UMLGeneralizableElement" eOpposite="#//core/UMLGeneralizableElement/generalizations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//core/UMLGeneralizableElement" transient="true" eOpposite="#//core/UMLGeneralizableElement/specializations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLInterface" eSuperTypes="#//core/UMLClassifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLModelElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="constrainingElements"
          upperBound="-1" eType="ecore:EClass behavioralelements.ecore#//collaborations/UMLCollaboration"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
          eType="ecore:EClass behavioralelements.ecore#//statemachines/UMLStateMachine"
          eOpposite="behavioralelements.ecore#//statemachines/UMLStateMachine/context"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EEnum enumerations.ecore#//VisibilityKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpecification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="clientDependencies" lowerBound="1"
          upperBound="-1" eType="#//core/UMLDependency" eOpposite="#//core/UMLDependency/clients"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="documents" upperBound="-1"
          eType="#//core/UMLDocument" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="supplierDependencies"
          lowerBound="1" upperBound="-1" eType="#//core/UMLDependency" eOpposite="#//core/UMLDependency/suppliers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateParameters" upperBound="-1"
          eType="#//core/UMLModelElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//core/UMLConstraint" eOpposite="#//core/UMLConstraint/constrainedElements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementationLocations"
          upperBound="-1" eType="#//core/UMLComponent" eOpposite="#//core/UMLComponent/residents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypes" upperBound="-1"
          eType="#//extensionmechanisms/UMLStereotype" eOpposite="#//extensionmechanisms/UMLStereotype/extendedElements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetFlows" upperBound="-1"
          eType="#//core/UMLFlow" eOpposite="#//core/UMLFlow/targets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFlows" upperBound="-1"
          eType="#//core/UMLFlow" eOpposite="#//core/UMLFlow/sources"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
          eType="#//core/UMLComment" eOpposite="#//core/UMLComment/annotatedElements"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
          eType="#//extensionmechanisms/UMLTaggedValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLOperation" eSuperTypes="#//core/UMLFeature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="occurrences" upperBound="-1"
          eType="ecore:EClass behavioralelements.ecore#//statemachines/UMLCallEvent"
          eOpposite="behavioralelements.ecore#//statemachines/UMLCallEvent/operation"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrency" eType="ecore:EEnum enumerations.ecore#//CallConcurrencyKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="raisedSignals" upperBound="-1"
          eType="ecore:EClass behavioralelements.ecore#//commonbehavior/UMLSignal"
          eOpposite="behavioralelements.ecore#//commonbehavior/UMLSignal/contexts"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1"
          eType="#//core/UMLClassifier" transient="true" eOpposite="#//core/UMLClassifier/operations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//core/UMLClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//core/UMLParameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLParameter" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EEnum enumerations.ecore#//ParameterDirectionKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
          eType="ecore:EClass behavioralelements.ecore#//activitygraphs/UMLObjectFlowState"
          eOpposite="behavioralelements.ecore#//activitygraphs/UMLObjectFlowState/parameters"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//core/UMLClassifier"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLFlow" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/targetFlows"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/sourceFlows"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLArtifact" eSuperTypes="#//core/UMLClassifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="implementationComponents"
          upperBound="-1" eType="#//core/UMLComponent" eOpposite="#//core/UMLComponent/implementations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLComment" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElements" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/comments"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="datatypes" nsURI="http:///foundation/datatypes.ecore" nsPrefix="foundation.datatypes">
    <eClassifiers xsi:type="ecore:EClass" name="UMLEnumeration" eSuperTypes="#//core/UMLDataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
          upperBound="-1" eType="#//datatypes/UMLEnumerationLiteral" containment="true"
          eOpposite="#//datatypes/UMLEnumerationLiteral/enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLEnumerationLiteral" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" lowerBound="1"
          eType="#//datatypes/UMLEnumeration" transient="true" eOpposite="#//datatypes/UMLEnumeration/literals"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLPrimitive" eSuperTypes="#//core/UMLDataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="UMLProgrammingLanguageDataType" eSuperTypes="#//core/UMLDataType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="extensionmechanisms" nsURI="http:///foundation/extensionmechanisms.ecore"
      nsPrefix="foundation.extensionmechanisms">
    <eClassifiers xsi:type="ecore:EClass" name="UMLStereotype" eSuperTypes="#//core/UMLGeneralizableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="extendedElements" upperBound="-1"
          eType="#//core/UMLModelElement" eOpposite="#//core/UMLModelElement/stereotypes"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredTags" upperBound="-1"
          eType="#//extensionmechanisms/UMLTaggedValue" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="definedTags" upperBound="-1"
          eType="#//extensionmechanisms/UMLTagDefinition" containment="true" eOpposite="#//extensionmechanisms/UMLTagDefinition/owner"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stereotypeConstraints"
          upperBound="-1" eType="#//core/UMLConstraint" containment="true" eOpposite="#//core/UMLConstraint/constrainedStereotype"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLTaggedValue" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//extensionmechanisms/UMLTagDefinition" eOpposite="#//extensionmechanisms/UMLTagDefinition/typedValues"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="UMLModelElement" upperBound="-1"
          eType="#//core/UMLModelElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referenceValue" upperBound="-1"
          eType="#//core/UMLModelElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UMLTagDefinition" eSuperTypes="#//core/UMLModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//extensionmechanisms/UMLStereotype"
          transient="true" eOpposite="#//extensionmechanisms/UMLStereotype/definedTags"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typedValues" upperBound="-1"
          eType="#//extensionmechanisms/UMLTaggedValue" eOpposite="#//extensionmechanisms/UMLTaggedValue/type"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
