<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generalmechanisms"
    nsURI="http:///umlmia.generalmechanisms.ecore" nsPrefix="generalmechanisms">
  <eClassifiers xsi:type="ecore:EClass" name="UMLClassifierImport" eSuperTypes="#//UMLElementImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedClassifier" lowerBound="1"
        eType="ecore:EClass foundation.ecore#//core/UMLClassifier" eOpposite="foundation.ecore#//core/UMLClassifier/importedInPackages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedInPackage" lowerBound="1"
        eType="#//UMLPackage" transient="true" eOpposite="#//UMLPackage/importedClassifiers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLElementImport" abstract="true" eSuperTypes="foundation.ecore#//core/UMLModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLModel" eSuperTypes="#//UMLPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertiesMetaClasses"
        upperBound="-1" eType="ecore:EClass properties.ecore#//UMLPropertyMetaClass"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLPackage" eSuperTypes="foundation.ecore#//core/UMLGeneralizableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClassifiers" upperBound="-1"
        eType="ecore:EClass foundation.ecore#//core/UMLClassifier" containment="true"
        eOpposite="foundation.ecore#//core/UMLClassifier/package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociations" upperBound="-1"
        eType="ecore:EClass foundation.ecore#//core/UMLAssociation" containment="true"
        eOpposite="foundation.ecore#//core/UMLAssociation/package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedClassifiers" upperBound="-1"
        eType="#//UMLClassifierImport" containment="true" eOpposite="#//UMLClassifierImport/importedInPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedPackages" upperBound="-1"
        eType="#//UMLPackageImport" containment="true" eOpposite="#//UMLPackageImport/importedInPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedInPackages" upperBound="-1"
        eType="#//UMLPackageImport" eOpposite="#//UMLPackageImport/importedPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="#//UMLPackage" transient="true" eOpposite="#//UMLPackage/ownedPackages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackages" upperBound="-1"
        eType="#//UMLPackage" containment="true" eOpposite="#//UMLPackage/package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLPackageImport" eSuperTypes="#//UMLElementImport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedInPackage" lowerBound="1"
        eType="#//UMLPackage" transient="true" eOpposite="#//UMLPackage/importedPackages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedPackage" lowerBound="1"
        eType="#//UMLPackage" eOpposite="#//UMLPackage/importedInPackages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UMLSubsystem" eSuperTypes="#//UMLPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInstantiable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
</ecore:EPackage>
